export const GET_LIST = 'GET_LIST';
export const GET_LIST_ERROR = 'GET_LIST_ERROR';
export const GET_LIST_SUCCESS = 'GET_LIST_SUCCESS';

export const GET_SEARCH_LISTS = 'GET_SEARCH_LISTS';
export const GET_SEARCH_LISTS_SUCCESS = 'GET_SEARCH_LISTS_SUCCESS';
export const GET_SEARCH_LISTS_ERROR = 'GET_SEARCH_LISTS_ERROR';
export const CLEAR_SEARCH_LIST= 'CLEAR_SEARCH_LIST';

export const GET_IMAGE_LISTS = 'GET_IMAGE_LISTS';
export const GET_IMAGE_LISTS_SUCCESS = 'GET_IMAGE_LISTS_SUCCESS';
export const GET_IMAGE_LISTS_ERROR = 'GET_IMAGE_LISTS_ERROR';
export const CLEAR_IMAGE_LIST= 'CLEAR_IMAGE_LIST';

export const SET_SEARCH_WORD = 'SET_SEARCH_WORD';